### PR TITLE
Add constructor for creating InputUtil from multiline String

### PR DESCRIPTION
**Pull request by dumazy**
Adds a useful constructor for testing the test cases

### CODE REVIEW

**Comment by S-ecki** [comment]
@dumazy This got me thinking: Maybe also automatically adding test files for the days, where you can easily paste in the small example input and the expected value might be useful. 
What do you think of this? 🤔

**Comment by dumazy** [comment]
Definitely, I was thinking that as well 🙌

**Comment by S-ecki** [comment]
I'm implementing something basic rn, want to review it?

**Comment by dumazy** [comment]
Sure, not at home right now but I should be able to check later today

**Pull request merged**
