### PR TITLE
added helper and better read input list

### PR DESCRIPTION
**Pull request by TesteurManiak**
* improved the method `getPerLine`
* added helper and all day arguments to `main.dart`

### CODE REVIEW

**Comment by TesteurManiak** [comment]
You're right I'll update the PR

**Comment by S-ecki** [comment]
@TesteurManiak Thanks for contributing!
Could you please also add the newly added CLI args to the readme?

**Comment by TesteurManiak** [comment]
Done @S-ecki 👍

**Review by S-ecki — APPROVED** [review]
thanks, looks great!

**Pull request merged**
